### ISSUE TITLE
Is the m40_ilrl is the trained model

### ISSUE THREAD

**Issue by XiangLiu0731** [dornik/reagent#2]
we download the pre-trained model from https://drive.google.com/drive/folders/1NyuwzIiJGyJsCkvEOnrziwrGN56uoTTj/m40_ilrl.zip and test it on modelnet40 with noise, but we get unreasonable results (MAE R is about 15). We also test m40_ilrl.zip on modelnet40 without any noise and the MAE R is about 1.1.

**Comment by dornik** [comment]
Hi,

Yes, `m40_ilrl.zip` is the model trained for a total of 100 epochs ("ours IL+RL" in the paper). I've just tried to replicate your issue by downloading the weights from Google Drive but running 

`python registration/eval.py --mode=ilrl --dataset=m40-model` 

yields the results reported in the paper for me with a MAE R of 1.47 and 1.34deg for `m40-model` and `m40-cat`, respectively. I've also tested without noise (i.e., changing the last parameter in [`eval.py:L127`](https://github.com/dornik/reagent/blob/f6497af6c62eadf8e34245cf6c2d9f87508c990b/registration/eval.py#L127) to `"clean"`) and get a MAE R of 1.18 and 0.82deg for `m40-model` and `m40-cat`, respectively. So those results seem consistent with yours and there might be an issue with your results using noise ("jitter"). 

Could you confirm that the settings in [`RandomJitter`](https://github.com/dornik/reagent/blob/f6497af6c62eadf8e34245cf6c2d9f87508c990b/dataset/augmentation.py#L128) are `scale=0.01` and `clip=0.05`? Might there be any other changes to the code? Are you using the ModelNet40 version provided [here](https://shapenet.cs.stanford.edu/media/modelnet40_ply_hdf5_2048.zip)?

**Comment by XiangLiu0731** [comment]
Thanks for your patient answer, I checked the code and I did change the noise parameters by mistake.
